<a href="https://colab.research.google.com/github/evelyncos/inteligencia_artificial/blob/main/acidentes_a%C3%A9reos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from datetime import datetime
import numpy as np
from sklearn.model_selection import train_test_split

URL = "https://raw.githubusercontent.com/paulozip/acidentes-aereos/master/dataset/ocorrencia.csv"

In [ ]:
dados = pd.read_csv(URL)
dados.head()

,codigo_ocorrencia,classificacao,tipo,localidade,uf,pais,aerodromo,dia_ocorrencia,horario,sera_investigada,comando_investigador,status_investigacao,numero_relatorio,relatorio_publicado,dia_publicacao,quantidade_recomendacoes,aeronaves_envolvidas,saida_pista,dia_extracao
0,47965,ACIDENTE,FALHA DO MOTOR EM VOO,ARIQUEMES,RO,BRASIL,SJOG,2013-05-05,11:00:00,***,SERIPA-7,NaN,NaN,NaN,NaN,0,1,NaN,2016-07-30
1,50313,INCIDENTE GRAVE,POUSO SEM TREM,CACOAL,RO,BRASIL,SSKW,2013-11-25,12:32:00,SIM,SERIPA-7,FINALIZADA,IG-209/CENIPA/2013,1.0,2014-04-07,0,1,NaN,2016-07-30
2,34078,ACIDENTE,PERDA DE CONTROLE NO SOLO,CEREJEIRAS,RO,BRASIL,****,2008-08-07,15:10:00,SIM,SERIPA-7,FINALIZADA,A - 517/CENIPA/2016,1.0,2016-07-07,0,1,1.0,2016-07-30
3,44988,ACIDENTE,POUSO LONGO,AMAJARI,RR,BRASIL,****,2011-08-11,17:00:00,SIM,SERIPA-7,FINALIZADA,A-105/CENIPA/2012,1.0,2012-09-20,4,1,NaN,2016-07-30
4,38855,ACIDENTE,PERDA DE CONTROLE EM VOO,ACEGU√Å,RS,BRASIL,****,2009-12-28,17:30:00,SIM,SERIPA-5,ATIVA,A DEFINIR,NaN,NaN,0,1,NaN,2016-07-30

In [ ]:
#apagar colunas

dados = dados.drop(columns = ["codigo_ocorrencia","classificacao","tipo","uf","localidade","pais","aerodromo","status_investigacao","comando_investigador","numero_relatorio","relatorio_publicado","quantidade_recomendacoes","quantidade_recomendacoes","dia_publicacao","saida_pista"], axis = 1)
dados.head()

  dia_ocorrencia   horario sera_investigada  aeronaves_envolvidas dia_extracao
0     2013-05-05  11:00:00              ***                     1   2016-07-30
1     2013-11-25  12:32:00              SIM                     1   2016-07-30
2     2008-08-07  15:10:00              SIM                     1   2016-07-30
3     2011-08-11  17:00:00              SIM                     1   2016-07-30
4     2009-12-28  17:30:00              SIM                     1   2016-07-30

In [ ]:
#troca de dados (sera_investigada)
a_trocar = {
    "NAO" : 0,
    "SIM" : 1
}
dados.sera_investigada= dados.sera_investigada.map(a_trocar)
dados.head()

,dia_ocorrencia,horario,sera_investigada,aeronaves_envolvidas,dia_extracao
0,2013-05-05,11:00:00,NaN,1,2016-07-30
1,2013-11-25,12:32:00,1.0,1,2016-07-30
2,2008-08-07,15:10:00,1.0,1,2016-07-30
3,2011-08-11,17:00:00,1.0,1,2016-07-30
4,2009-12-28,17:30:00,1.0,1,2016-07-30

In [ ]:
#fatiando os dados
x = dados[["dia_ocorrencia", "horario","horario"]]
y = dados ["sera_investigada"]

SEED = 20
np.random.seed(SEED)
treino_x, teste_x, treino_y, teste_y = train_test_split(x, y, test_size = 0.30)
                                                      
print(f"Treinamento: {len(treino_x)} | Teste: {len(teste_x)}")

Treinamento: 1418 | Teste: 609

In [ ]:
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score

modelo = LinearSVC()
modelo.fit(treino_x, treino_y)

previsoes = modelo.predict (teste_x)

acuracia = accuracy_score(teste_y, previsoes)*100
print (f"Acuracia : {acuracia:.2f}")

ValueError: ignored